[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  REACT_APP_API_URL = "https://denimora.onrender.com/api"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 