# Generated by Django 5.2.3 on 2025-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price after applying discount', max_digits=10, null=True),
        ),
    ]
