# Generated by Django 5.2.3 on 2025-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_discount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_active',
            field=models.BooleanField(default=False, help_text='Enable/disable discount for this product'),
        ),
    ]
